/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 9.1.0   2018-11-28

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

// https://stm32f4-discovery.net/2015/01/properly-set-clock-speed-stm32f4xx-devices/
int main(void)
{
  int i = 0;

  while (1)
  {
	i++;
  }
}
